CREATE TABLE Project (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  imgUrl VARCHAR(255),
  gitUrl VARCHAR(255),
  status VARCHAR(255)
);
CREATE TABLE post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  reference VARCHAR(255),
  type VARCHAR(255)
);